export default {
  generalSettings: {
    id: "list-3tma2kZIi6z0YwA8",
    padding: 10,
    height: null,
    width: null,
    responsive: true,
    postsNumber: 25,
    postsShowNumber: 0,
    backgroundColor: "#f5f5f7",
    autoPlay: false,
    speed: null,
    fontFamily: "",
    openNewWindow: true,
    cardTheme: null,
    imageAutoHeight: false,
    __typename: "EmbedGeneralSettings",
  },
  titleSettings: {
    id: "list-3tma2kZIi6z0YwA8",
    enable: true,
    fontSize: 24,
    color: "#000000",
    backgroundColor: "#ffffff",
    __typename: "EmbedTitleSettings",
  },
  cardSettings: {
    id: "list-3tma2kZIi6z0YwA8",
    backgroundColor: "#fff",
    cardShowTitle: true,
    cardTitleFontSize: 18,
    cardTitleColor: "#121314",
    cardShowImage: true,
    cardImageHeight: null,
    cardShowDescription: true,
    cardDescriptionFontSize: 14,
    cardDescriptionLines: 2,
    cardDescriptionColor: "#6a6a75",
    cardSocialSharing: false,
    cardShowFooter: true,
    cardFooterColor: "#8899a6",
    cardImageLink: false,
    __typename: "EmbedCardSettings",
  },
};
